### ISSUE TITLE
Aggregate grade bug (not sure what max calculates here)

### ISSUE THREAD

**Issue by dominopizzaaaa** [AY2425S1-CS2103T-T08-4/tp#100]
Bernice has a midterm score of 84%, Alex has final score of 90%, 84% is outputted.

Suggestion: max and min should take into account only the overall score (with weightage taken into account too)
![Screenshot 2024-10-31 at 3 42 52 PM](https://github.com/user-attachments/assets/118680dc-6165-403f-921a-154a816ac4c5)

**Comment by juancarlovieri** [comment]
Expected behaviour
