### ISSUE TITLE
Incorrect date parsing

### ISSUE THREAD

**Issue by Oceankoh** [AY2425S1-CS2103T-T08-4/tp#111]
Trying to mark attendance on 29 Feburary 2023, or 30 Feburary 2023, or 31 February 2024 marks the attendnace on 28/02/2024 or 29/02/2024 instead of returning invalid date format.

**Comment by izruff** [comment]
This is also what happens when trying to mark attendance on the 31st date of *any* month (it is automatically set to 30th, unless it's February).

Also, using 24:00 for the HH:mm part actually increments the date by 1 (so 01/01/2024 24:00 gets rewritten as 02/01/2024 00:00).
