### ISSUE TITLE
Able to bypass 100% grade weightage

### ISSUE THREAD

**Issue by Oceankoh** [AY2425S1-CS2103T-T08-4/tp#117]
If the floating point is small enough, you can exceed the 100% weightage restriction. This is not significant enough to affect scores

steps to reproduce
1. `addGrade 2 n/test full s/100 w/`100`
2. `addGrade 2 n/test broken s/100 w/0.000001`

![image](https://github.com/user-attachments/assets/323b5e46-b001-4827-8e76-2f083b631b6e)

**Comment by dominopizzaaaa** [comment]
nice catch
