### ISSUE TITLE
[PE-D][Tester A] Expected Output of add feature ambiguous

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-4/tp#196]
The expected output picture provided only shows the final result of the add command presumably, but I do not know what input led to this expected output. Can be confusing.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: FlyingDonkeys/ped#2

**Comment by juancarlovieri** [comment]
@izruff can you help add the input for the expected output for each commands

**Comment by izruff** [comment]
This is already resolved in #189 (the UG PDF was outdated)
