### ISSUE TITLE
[PE-D][Tester C] General formatting of content in PersonCard

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-4/tp#200]
There are many lines in PersonCard containing different information. For instance, some are related to grades and some are related to attendances. However, there are no spaces between the lines which could give the user a hard time in picking out relevant information. 

One possible improvement would be to insert blank lines such that lines containing relevant information are grouped. See the image attached below:

![image.png](https://raw.githubusercontent.com/Xczheng0105/ped/main/files/c01d65b3-e882-4925-94fa-7ffafa3ae6d5.png)

Here the red lines are potential places for an empty line. Another method might be to use a UI element similar to that of Tags to group the information accordingly.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Xczheng0105/ped#1

**Comment by juancarlovieri** [comment]
This is a UI-related issue.

It is currently in feature freeze so we are not going to do it.
