### ISSUE TITLE
[PE-D][Tester E] Broken hyperlinks in DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-4/tp#222]
The hyperlinks of many sections (`Main`, `MainApp`, etc) redirect to AB-3’s repository instead of TAHub’s.

for instance, here:

![image.png](https://raw.githubusercontent.com/tanwartushar/ped/main/files/51b3457a-1855-4046-b336-3e80a6d41ac0.png)
(Hyperlinks at `Main`, `MainApp` redirect to [here](https://github.com/se-edu/addressbook-level3/blob/master/src/main/java/seedu/address/Main.java) and [here](https://github.com/se-edu/addressbook-level3/blob/master/src/main/java/seedu/address/MainApp.java) respectively)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: tanwartushar/ped#6

**Comment by hpcman** [comment]
The DG is outdated. It's already fixed in pull request #190.
