### ISSUE TITLE
[PE-D][Tester F] Can add invalid email

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-4/tp#223]
Can consider parsing for `.com` or other domain endings at the end
![Picture8.png](https://raw.githubusercontent.com/testing1234567891011121314/ped/main/files/b1e835e4-ba3f-431e-92b8-d9cb09f92f1a.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: testing1234567891011121314/ped#6

**Comment by Oceankoh** [comment]
Hi the email `john@ohn.com.com.com.com.com` is in fact a valid email. In fact it is not true that you need a TLD for an email to be valid. With a local network mailserver, an email like a@localmailserver1 is valid as well.
