### ISSUE TITLE
[PE-D][Tester F] Person that does not exist is mistaken as existing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-4/tp#226]
There was an issue faced when adding a person that does not exist
![Picture9.png](https://raw.githubusercontent.com/testing1234567891011121314/ped/main/files/ac5239e2-a810-4f24-a12a-f94c2abc0953.png)

![Picture10.png](https://raw.githubusercontent.com/testing1234567891011121314/ped/main/files/33a4b6fb-2fbf-4628-aeff-fd004e652c9d.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: testing1234567891011121314/ped#7

**Comment by izruff** [comment]
Could not reproduce; have commented on the original issue for clarification.

**Comment by izruff** [comment]
Need to add in UG that a person is uniquely identified by email and course (since this is not mentioned in error message).
