### ISSUE TITLE
[PE-D][Tester E] UG: UI image (vs actual) inconsistencies - status bar (footer) 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-4/tp#242]
In the documentation, the footer displays `…./addressbook.json`
whereas the actual product displays `…../TAHub.json`

example:
docs:

![image.png](https://raw.githubusercontent.com/tanwartushar/ped/main/files/aa1371bf-3b6b-4dd0-9f76-0148ec5c0981.png)

whereas, in the application:

![image.png](https://raw.githubusercontent.com/tanwartushar/ped/main/files/f1d3c68a-64b2-4fb5-a0ae-043439120ae7.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: tanwartushar/ped#9

**Comment by izruff** [comment]
I believe we have fixed this at some point, but perhaps the UG PDF was not imported from the latest version.
