### ISSUE TITLE
[PE-D][Tester D] mark does not meet the requirement of the Task

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-4/tp#244]
![image.png](https://raw.githubusercontent.com/brendanng7/ped/main/files/1f6c8875-b931-4246-8f01-81e8477f579c.png)
I am able to mark attendance for students in the future. Maybe there should be an error message stopping TAs from marking students attendance in the future.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: brendanng7/ped#11

**Comment by Oceankoh** [comment]
Not a bug.

**Comment by izruff** [comment]
While this is not a bug, maybe we can put this as a note in the UG?
