### ISSUE TITLE
[PE-D][Tester F] Can add weird years for attendance

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-4/tp#250]
Can consider parsing the attendance datetimes in case of typos
![image.png](https://raw.githubusercontent.com/testing1234567891011121314/ped/main/files/fd456076-3fe4-48b5-a55d-08b7f0827e7e.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: testing1234567891011121314/ped#11

**Comment by Oceankoh** [comment]
Hi, thanks for the bug report. However, we do not consider this a bug. The year 28/02/1202 is a valid date. Restricting dates to a valid set of years would not fix the issue of typos as well since a TA can accidentally put 2025 or 2023 as a typo.
