### ISSUE TITLE
[PE-D][Tester E] Commands (ex: mark, add) have inconsistent error messages

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-4/tp#252]
For a large index number, this error message is received:

![Pasted Graphic 1.png](https://raw.githubusercontent.com/tanwartushar/ped/main/files/049a12d3-a481-47a2-9447-360d5f176514.png)￼

However, for an even larger (out of bounds) index number, this error message is received:

![image.png](https://raw.githubusercontent.com/tanwartushar/ped/main/files/4d7bfb49-18e7-4955-8a01-551b395bbdf6.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tanwartushar/ped#11

**Comment by Oceankoh** [comment]
The error message is valid. Since the command exceeded the bounds defined for INDEX in the user guide, the command format is not followed and the error message is appropriate
